language: go
go:
- 1.15.3
script:
- go test
- go build
deploy:
  provider: heroku
  on:
    branch: main
  api_key:
    secure: DDcUH82nzerWIokZ/IBUUHZjt/hP2wErSwccoiPUFnQCsR5uBqFi4Gi+t1gCJMjLka8LMBSIdhvzDvWHXxixMsv1dbuKkPV2SLRPTTbwU+tKut+6ga1O3JS28gEStJxpbMz6Ru7aiYYJfgoKvXbI3RmO1Ilh/r4R3r2J3vsIl23ffyXiTGj8oVZ8elIbTjb8nwFne9NrxuSNpnX+gSHIZsR7xd8W/GjFKBTAGEHvmiw41VqFC3i0naMIlSTVN6lgHLyVOCzfQTmyNSyP6r6KeJaS5jRHHbTm8m+F0pOJspAo5oZUBq9ZYCfgCsoswbgytfilBFyojNyrFIt8ngwql0pSPdFRKjK5ImA+slielOBYCGAVtjYKeaZwPE5kkP/WTXlt+N5v2gSK6pZwCd0M0GO670FD+6xUIFI7iSAc9a8ksXp/hnD8DPW2pmhBdjQdeGBR9y9Z25og8s9vOT43iVlF2MstZynQ6DuRemzqE4xgbuVN6DvuG0wUgUNSzw6ySTcz/XxGNbbOmAAQ05tVAvSucogxPa5JpCXq+uO/dfi2snxhOb51qxGauhHBb+HuWj5zt7c/dqQOIJjyAoerINc063fOXPVHdyQkkpKpM4rxj4fkLMXpdOWtq4jgiVIyyksvga8UNY/CZZbIw31+/XCMYJOGTjeetOSEtyMZi9o=
  app:
    secure: HwIT3YGK65uG0EKx4Hn5jwQHuxOl6r/AaM2t3O415W+8EB7VsIwfPdeiMeTIXVMxmJinPcJ+eNZ4AP3dNIk7p3tObN2sl8B1XDgfcPn/D0X7MnZT+SPbAxle59etGKEg8mM6v/+o5qS2JPEzOyL9YWlDDHHhmLhTUhsfmFkDGSuo5fejB4tnGDvsMN6jPAhhg2ji5otGSwZpyYp+TrAfARQZX1CZ1y7ewLYaUW+JtGfYSpXxS4c4Hs4w3iV1rQ2nNCLImGklBKJPnsEiSGliRtTfgfzXnHdYYvVxqiwtrY5+/ZkFL6KaXzZMhPio3Jldehzlh2/G9IpESmTnJgXR1WJAEgNcWCuoqq8MXvEsDuL6r/cLzJGXrSQRgFe4GycDECX3r05a0NNfS1GWTFDvy16DJCu6xgEoASyzDE0Js0HTeEkJrScuTpy8MTcwZNYUG8I7ziQCYjh3a7rqSTw8fCZhZSSwb1/Az/sQTCNyvqVUYAQ/R6M0w7XSOAUyiRW+vxo7C3K0XsgZTgKQGytg6PWFchBnbs0jh8RDaCV/sm2FgpLedVujvQHJpSgmSWi57rXREt+nLVcZRwhl1sqh5WDdGo7QYDCZuA4VSKM7IFlXJWgJyZMFbtXygkGA8fZpqjNAgqU9RJ4CB9qYVItNwj1OUp0k7xPkMyesJsQOomc=
